theme: jekyll-theme-modernist
title: Alekha.Net
description: mobile-first, knowledge base on top of plain text Markdown and remote sync 
copyright: © 2021 Alekha.Net All Rights Reserved

nav:
 - name: Home
   link: /
 - name: Download app
   link: https://play.google.com/store/apps/details?id=com.alekha.net&hl=en_IN&gl=US
   
   
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alekhanetweb/website"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Download App"
      icon: "fab fa-fw fa-download"
      url: "https://play.google.com/store/apps/details?id=com.alekha.net"

# copyright  : © 2021 jasperVincent All Rights Reserved
# theme: jekyll-theme-modernist

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
