theme: jekyll-theme-modernist
title: Alekha.Net
description: movement for cognitive introspection
# show_downloads: false
# footer_url: "https://github.com/alekhanetweb"
# footer_text: "Copyright Alekha.Net team"
copyright  : © 2021 Alekha.Net All Rights Reserved
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alekhanetweb/website"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

nav:
 - name: Home
   link: /
 - name: About
   link: /
#  - name: En
#    link: /about/
