theme: jekyll-theme-modernist
title: Alekha.Net
description: movement for cognitive introspection
# copyright: © 2021 Alekha.Net All Rights Reserved
copyright_name: © 2021 Alekha.Net All Rights Reserved

nav:
 - name: Home
   link: /
 - name: About
   link: /
   
   
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alekhanetweb/website"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# copyright  : © 2021 jasperVincent All Rights Reserved
# theme: jekyll-theme-modernist

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
